# -*- coding: utf-8 -*-
"""Copy of Banking - EDA Case Study

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VP5cDcnZcF3-dtzHv4-_qBnzTGSmhr3X
"""



"""END GOAL

Our end goal is to do the risk analysis and also try to show important KPI's to our managers and stakeholders, These Imp KPI's have been shown in Python as well, but for presenting to clients and all we need power BI or Tablue dashboard for presenting.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

df = pd.read_csv('/content/Banking.csv')
df.head()

"""# New Section"""

df.shape

df.info()

# generative descriptive statistics for dataframe
df.describe()

bins = [0,100000,300000,float('inf')]
labels = ['Low','Medium','High']

df['Income Band'] = pd.cut(df['Estimated Income'], bins=bins, labels=labels, right=False)

df['Income Band'].value_counts().plot(kind='bar')

#examine the distribution of unique categories in categorical columns
categorical_cols = df[['BRId','GenderId','Amount of Credit Cards','Nationality','Occupation','Fee Structure','Loyalty Classification','Properties Owned','Risk Weighting','IAId','Income Band']].columns

for col in categorical_cols:
  print(f"Value Counts for '{col}':")
  display(df[col].value_counts())
  print('\n')

"""Univariant Analysis"""

for i, predictor in enumerate(df[['BRId','GenderId','Amount of Credit Cards','Nationality','Occupation','Fee Structure','Loyalty Classification','Properties Owned','Risk Weighting','IAId','Income Band']].columns):
  plt.figure(i)
  sns.countplot(data=df, x=predictor)

"""Bivariant Analysis"""

for i, predictor in enumerate(df[['BRId','GenderId','Amount of Credit Cards','Nationality','Occupation','Fee Structure','Loyalty Classification','Properties Owned','Risk Weighting','IAId','Income Band']].columns):
  plt.figure(i)
  sns.countplot(data=df, x=predictor, hue = 'GenderId')

for i, predictor in enumerate(df[['BRId','GenderId','Amount of Credit Cards','Nationality','Occupation','Fee Structure','Loyalty Classification','Properties Owned','Risk Weighting','IAId','Income Band']].columns):
  plt.figure(i)
  sns.countplot(data=df, x=predictor, hue = 'Nationality')

#histplot of value counts for different occurpation

for col in categorical_cols:
  if col == 'Occupation':
    continue
  plt.figure(figsize=(10,6))
  sns.histplot(df[col])
  plt.title(f'Distribution of {col}')
  plt.xlabel(col)
  plt.ylabel('count')
  plt.show()

"""Numerical Analysis"""

numerical_cols = ['Estimated Income', 'Superannuation Savings']

#universal analysis
plt.figure(figsize=(15,10))
for i, col in enumerate(numerical_cols):
  plt.subplot(2,1,i+1)
  sns.histplot(df[col], kde=True)
  plt.title(col)
sns.pairplot(df[numerical_cols])
plt.show()

numerical_cols = ['Estimated Income', 'Credit Card Balance']

#universal analysis
plt.figure(figsize=(15,10))
for i, col in enumerate(numerical_cols):
  plt.subplot(2,1,i+1)
  sns.histplot(df[col], kde=True)
  plt.title(col)
sns.pairplot(df[numerical_cols])
plt.show()

numerical_cols = ['Estimated Income', 'Superannuation Savings', 'Credit Card Balance', 'Bank Deposits', 'Checking Accounts','Saving Accounts','Foreign Currency Account','Bank Loans','Business Lending']

#universal analysis
plt.figure(figsize=(15,10))
for i, col in enumerate(numerical_cols):
  plt.subplot(4,3,i+1)
  sns.histplot(df[col], kde=True)
  plt.title(col)
plt.show()

"""Heat Maps"""

numerical_cols = ['Estimated Income', 'Superannuation Savings', 'Credit Card Balance', 'Bank Deposits', 'Checking Accounts','Saving Accounts','Foreign Currency Account','Bank Loans','Business Lending']

correlation_matrix = df[numerical_cols].corr()

plt.figure(figsize=(12,12))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt = '.2f')
plt.title('Correlation Heatmap')
plt.show()

"""# Insights of EDA:

1. the Strongest positive correlation occur among 'Bank Deposits" with "Checking Acocounts". 'Savings Accounts' anf 'Foreign Currency Account' Indicating that customers who maintain high balances in one account type often hold substantial amount/funds across other accounts as well

Analysis is done now final thing is to present the analysis using tools.

check data -> no of pages i want -> sketch -> canva or tool for background -> onboard all numbers and columns etc.

1 page for Loan analysis
2 page for deposist
3 summar
4 Ask QA
and HOME page at starting
"""

